### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 4DeepThought2** [Anze-/ComfyUI-OIDN#1]
This seems so simple, but the image is no different after it runs through the OIDN node.

**Comment by Anze-** [comment]
Sorry about that! Did you try with the reference image?

**Comment by 4DeepThought2** [comment]
Interesting.  Its working with the reference image, but not a single other image, yet.  Ive tried about 10.

**Comment by 4DeepThought2** [comment]
ok its working.  Looks like it needs to be a specific kind of noise/grain for it to remove.  Otherwise it just ignores it.  Even if its very grainy.

**Comment by Anze-** [comment]
Yes, this model works really well but only on a very specific kind of noise
which is the one commonly obtained by ray tracing!
